[versions]
lombok = "1.18.42"
log4j = "2.24.3"
jackson = "3.0.4"
junit = "6.0.2"
javafx = "24"
javafx-plugin = "0.1.0"

[libraries]
# Logging
log4j-bom = { module = "org.apache.logging.log4j:log4j-bom", version.ref = "log4j" }
log4j-api = { module = "org.apache.logging.log4j:log4j-api" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core" }

# Lombok
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

# Jackson
jackson-databind = { module = "tools.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-dataformat-yaml = { module = "tools.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }

# Testing
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

[bundles]
log4j = ["log4j-api", "log4j-core"]
testing = ["junit-jupiter"]

[plugins]
lombok = { id = "io.freefair.lombok", version = "9.2.0" }
javafx = { id = "org.openjfx.javafxplugin", version.ref = "javafx-plugin" }
